DROP TABLE IF EXISTS projects CASCADE;
CREATE TABLE projects (
   id SERIAL PRIMARY KEY,
   name VARCHAR(256) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS steps CASCADE;
CREATE TABLE steps (
   id SERIAL PRIMARY KEY,
   name VARCHAR(256) NOT NULL,
   fk_project INTEGER REFERENCES projects(id) ON DELETE CASCADE ON UPDATE CASCADE,
   fk_parent INTEGER REFERENCES steps(id) ON DELETE SET NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   planned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   finished_at TIMESTAMP,
   is_finished BOOLEAN NOT NULL DEFAULT FALSE
);

DROP TABLE IF EXISTS incomes CASCADE;
CREATE TABLE incomes (
   fk_project INTEGER REFERENCES projects(id) ON DELETE CASCADE ON UPDATE CASCADE,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   sum REAL
);

DROP TABLE IF EXISTS activity CASCADE;
CREATE TABLE activity (
   fk_step INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE ON UPDATE CASCADE,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   spent SMALLINT NOT NULL DEFAULT 0
);
